name: "[CD] Continuous Delivery"

# Sempre que tiver um commit ou um PR for aberto
# on:
#   push:
#     branches: [ main ]
on:
  pull_request:
    types: [opened, synchronize]

env:
  VERCEL_ORG_ID: AedfOWQxHk9Cue8P10t1lT6s
  VERCEL_PROJECT_ID: prj_b6ALOMIwj4dmvixSpDAA49OyGbPc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =================
      - name: "Debug"
        run: |
          ls -la
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Deploy"
        run: "npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}"
